- name: restart machine
  shell: /sbin/shutdown -r +1  "Ansible updates triggered"
  sudo: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=80 timeout=10 connect_timeout=5
  sudo: false
